In [2]:
import pandas as pd

In [11]:
pl23 = pd.read_csv('pl23-24.csv')
dfpl23 = pl23.iloc[:, 0:-82]

In [50]:
#dfpl23 = dfpl23.drop('Div', axis=1)
dfpl23

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,AF,HC,AC,HY,AY,HR,AR,HomeTablePos,AwayTablePos,TablePosDiff
0,2023-08-11,20:00,Burnley,Man City,0,3,A,0,2,A,...,8,6,5,0,0,1,0,10,10,0
1,2023-08-12,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,H,...,12,8,3,2,2,0,0,10,10,0
2,2023-08-12,15:00,Bournemouth,West Ham,1,1,D,0,0,D,...,14,10,4,1,4,0,0,10,10,0
3,2023-08-12,15:00,Brighton,Luton,4,1,H,1,0,H,...,12,6,7,2,2,0,0,10,10,0
4,2023-08-12,15:00,Everton,Fulham,0,1,A,0,0,D,...,6,10,4,0,2,0,0,10,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2024-05-19,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,H,...,8,2,4,1,4,0,0,13,4,-9
376,2024-05-19,16:00,Liverpool,Wolves,2,0,H,2,0,H,...,11,10,2,1,1,0,1,3,14,11
377,2024-05-19,16:00,Luton,Fulham,2,4,A,1,2,A,...,20,4,4,5,4,0,0,18,15,-3
378,2024-05-19,16:00,Man City,West Ham,3,1,H,2,1,H,...,12,11,2,0,1,0,0,2,9,7
379,2024-05-19,16:00,Sheffield United,Tottenham,0,3,A,0,1,A,...,9,2,6,2,0,0,0,20,6,-14

In [51]:
### Team-centric dataframe, extra column for points ###
dfpl23['Date'] = pd.to_datetime(dfpl23['Date'], dayfirst=True)
dfpl23 = dfpl23.sort_values(['Date', 'Time']).reset_index(drop=True)

# -------------------------
# HOME TEAM PERSPECTIVE
# -------------------------

home_df = pd.DataFrame({
    'Date': dfpl23['Date'],
    'Time': dfpl23['Time'],
    'Team': dfpl23['HomeTeam'],
    'Opponent': dfpl23['AwayTeam'],
    'Venue': 'H',

    'GoalsFor': dfpl23['FTHG'],
    'GoalsAgainst': dfpl23['FTAG'],

    'HTGoalsFor': dfpl23['HTHG'],
    'HTGoalsAgainst': dfpl23['HTAG'],

    'Shots': dfpl23['HS'],
    'ShotsAgainst': dfpl23['AS'],

    'ShotsOnTarget': dfpl23['HST'],
    'ShotsOnTargetAgainst': dfpl23['AST'],

    'Corners': dfpl23['HC'],
    'CornersAgainst': dfpl23['AC'],

    'Fouls': dfpl23['HF'],
    'FoulsAgainst': dfpl23['AF'],

    'YellowCards': dfpl23['HY'],
    'YellowCardsAgainst': dfpl23['AY'],

    'RedCards': dfpl23['HR'],
    'RedCardsAgainst': dfpl23['AR']
})

# Result from home team's perspective
home_df['Result'] = dfpl23['FTR'].map({
    'H': 'W',
    'D': 'D',
    'A': 'L'
})

# -------------------------
# AWAY TEAM PERSPECTIVE
# -------------------------

away_df = pd.DataFrame({
    'Date': dfpl23['Date'],
    'Time': dfpl23['Time'],
    'Team': dfpl23['AwayTeam'],
    'Opponent': dfpl23['HomeTeam'],
    'Venue': 'A',

    'GoalsFor': dfpl23['FTAG'],
    'GoalsAgainst': dfpl23['FTHG'],

    'HTGoalsFor': dfpl23['HTAG'],
    'HTGoalsAgainst': dfpl23['HTHG'],

    'Shots': dfpl23['AS'],
    'ShotsAgainst': dfpl23['HS'],

    'ShotsOnTarget': dfpl23['AST'],
    'ShotsOnTargetAgainst': dfpl23['HST'],
    

    'Corners': dfpl23['AC'],
    'CornersAgainst': dfpl23['HC'],

    'Fouls': dfpl23['AF'],
    'FoulsAgainst': dfpl23['HF'],

    'YellowCards': dfpl23['AY'],
    'YellowCardsAgainst': dfpl23['HY'],

    'RedCards': dfpl23['AR'],
    'RedCardsAgainst': dfpl23['HR']
})

# Result from away team's perspective
away_df['Result'] = dfpl23['FTR'].map({
    'A': 'W',
    'D': 'D',
    'H': 'L'
})

# -------------------------
# COMBINE
# -------------------------

team_df = pd.concat([home_df, away_df], ignore_index=True)

# Points column
team_df['Points'] = team_df['Result'].map({
    'W': 3,
    'D': 1,
    'L': 0
})

# Sort chronologically
team_df = team_df.sort_values(
    ['Team', 'Date', 'Time']
).reset_index(drop=True)

In [52]:
team_df

,Date,Time,Team,Opponent,Venue,GoalsFor,GoalsAgainst,HTGoalsFor,HTGoalsAgainst,Shots,...,Corners,CornersAgainst,Fouls,FoulsAgainst,YellowCards,YellowCardsAgainst,RedCards,RedCardsAgainst,Result,Points
0,2023-08-12,12:30,Arsenal,Nott'm Forest,H,2,1,2,0,15,...,8,3,12,12,2,2,0,0,W,3
1,2023-08-21,20:00,Arsenal,Crystal Palace,A,1,0,0,0,14,...,8,1,10,14,1,2,1,0,W,3
2,2023-08-26,15:00,Arsenal,Fulham,H,2,2,0,1,19,...,8,3,6,5,0,3,0,1,D,1
3,2023-09-03,16:30,Arsenal,Man United,H,3,1,1,1,17,...,12,3,8,7,2,3,0,0,W,3
4,2023-09-17,16:30,Arsenal,Everton,A,1,0,0,0,13,...,11,1,10,12,1,1,0,0,W,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,2024-04-24,19:45,Wolves,Bournemouth,H,0,1,0,1,15,...,8,12,10,17,4,1,0,1,L,0
756,2024-04-27,15:00,Wolves,Luton,H,2,1,1,0,13,...,4,4,14,14,3,1,0,0,W,3
757,2024-05-04,17:30,Wolves,Man City,A,1,5,0,3,2,...,0,6,17,4,4,0,0,0,L,0
758,2024-05-11,15:00,Wolves,Crystal Palace,H,1,3,0,2,13,...,8,3,13,12,3,2,0,1,L,0
759,2024-05-19,16:00,Wolves,Liverpool,A,0,2,0,2,4,...,2,10,11,14,1,1,1,0,L,0

In [56]:
### introduce positions and position difference features ###
dfpl23 = dfpl23.sort_values(['Date', 'Time']).reset_index(drop=True)

teams = sorted(
    set(dfpl23['HomeTeam']).union(set(dfpl23['AwayTeam']))
)

# League table
table = pd.DataFrame(index=teams)
table['Pts'] = 0
table['GD'] = 0
table['GF'] = 0

played = {team: 0 for team in teams}

home_pos = []
away_pos = []

for _, row in dfpl23.iterrows():

    home = row['HomeTeam']
    away = row['AwayTeam']

    # Current standings BEFORE this match
    standings = (
        table
        .sort_values(
            ['Pts', 'GD', 'GF'],
            ascending=False
        )
        .reset_index()
    )

    standings['Position'] = standings.index + 1

    pos_lookup = dict(
        zip(standings['index'], standings['Position'])
    )

    # First 3 matches => average position
    home_pos.append(
        10 if played[home] < 3 else pos_lookup[home]
    )

    away_pos.append(
        10 if played[away] < 3 else pos_lookup[away]
    )

    # Update table AFTER storing positions
    hg = row['FTHG']
    ag = row['FTAG']

    table.loc[home, 'GF'] += hg
    table.loc[home, 'GD'] += hg - ag

    table.loc[away, 'GF'] += ag
    table.loc[away, 'GD'] += ag - hg

    if hg > ag:
        table.loc[home, 'Pts'] += 3
    elif hg < ag:
        table.loc[away, 'Pts'] += 3
    else:
        table.loc[home, 'Pts'] += 1
        table.loc[away, 'Pts'] += 1

    played[home] += 1
    played[away] += 1

# Add to original match dataframe
dfpl23['HomeTablePos'] = home_pos
dfpl23['AwayTablePos'] = away_pos
dfpl23['TablePosDiff'] = (
    dfpl23['AwayTablePos']
    - dfpl23['HomeTablePos']
)

In [57]:
# Home team rows
home_df['TeamTablePos'] = dfpl23['HomeTablePos']
home_df['OpponentTablePos'] = dfpl23['AwayTablePos']

# Away team rows
away_df['TeamTablePos'] = dfpl23['AwayTablePos']
away_df['OpponentTablePos'] = dfpl23['HomeTablePos']

# Difference from team's perspective
home_df['TablePosDiff'] = (
    home_df['OpponentTablePos']
    - home_df['TeamTablePos']
)

away_df['TablePosDiff'] = (
    away_df['OpponentTablePos']
    - away_df['TeamTablePos']
)

In [58]:
### add the new features to the combined team dataframe ###
team_df = pd.concat([home_df, away_df], ignore_index=True)

team_df['Points'] = team_df['Result'].map({
    'W': 3,
    'D': 1,
    'L': 0
})

team_df = team_df.sort_values(
    ['Team', 'Date', 'Time']
).reset_index(drop=True)

In [59]:
team_df

,Date,Time,Team,Opponent,Venue,GoalsFor,GoalsAgainst,HTGoalsFor,HTGoalsAgainst,Shots,...,FoulsAgainst,YellowCards,YellowCardsAgainst,RedCards,RedCardsAgainst,Result,TeamTablePos,OpponentTablePos,TablePosDiff,Points
0,2023-08-12,12:30,Arsenal,Nott'm Forest,H,2,1,2,0,15,...,12,2,2,0,0,W,10,10,0,3
1,2023-08-21,20:00,Arsenal,Crystal Palace,A,1,0,0,0,14,...,14,1,2,1,0,W,10,10,0,3
2,2023-08-26,15:00,Arsenal,Fulham,H,2,2,0,1,19,...,5,0,3,0,1,D,10,10,0,1
3,2023-09-03,16:30,Arsenal,Man United,H,3,1,1,1,17,...,7,2,3,0,0,W,6,10,4,3
4,2023-09-17,16:30,Arsenal,Everton,A,1,0,0,0,13,...,12,1,1,0,0,W,5,18,13,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,2024-04-24,19:45,Wolves,Bournemouth,H,0,1,0,1,15,...,17,4,1,0,1,L,11,13,2,0
756,2024-04-27,15:00,Wolves,Luton,H,2,1,1,0,13,...,14,3,1,0,0,W,13,18,5,3
757,2024-05-04,17:30,Wolves,Man City,A,1,5,0,3,2,...,4,4,0,0,0,L,11,2,-9,0
758,2024-05-11,15:00,Wolves,Crystal Palace,H,1,3,0,2,13,...,12,3,2,0,1,L,13,15,2,0
759,2024-05-19,16:00,Wolves,Liverpool,A,0,2,0,2,4,...,14,1,1,1,0,L,14,3,-11,0

In [64]:
### Compute rolling averages ###
rolling_cols = [
    'TablePosDiff',
    'GoalsFor',
    'Shots',
    'ShotsOnTarget',
    'Corners',
    'Fouls'
]

for col in rolling_cols:

    team_df[f'{col}_Rolling5'] = (
        team_df
        .groupby(['Team', 'Venue'])[col]
        .transform(
            lambda x: x.shift(1)
                      .rolling(window=5, min_periods=1)
                      .mean()
        )
    )

for col in rolling_cols:

    team_df[f'{col}_Rolling10'] = (
        team_df
        .groupby(['Team', 'Venue'])[col]
        .transform(
            lambda x: x.shift(1)
                      .rolling(window=10, min_periods=1)
                      .mean()
        )
    )

for col in rolling_cols:

    team_df[f'{col}_Rolling5_all'] = (
        team_df
        .groupby(['Team'])[col]
        .transform(
            lambda x: x.shift(1)
                      .rolling(window=5, min_periods=1)
                      .mean()
        )
    )

for col in rolling_cols:

    team_df[f'{col}_Rolling10_all'] = (
        team_df
        .groupby(['Team'])[col]
        .transform(
            lambda x: x.shift(1)
                      .rolling(window=10, min_periods=1)
                      .mean()
        )
    )

In [65]:
team_df

,Date,Time,Team,Opponent,Venue,GoalsFor,GoalsAgainst,HTGoalsFor,HTGoalsAgainst,Shots,...,Shots_Rolling5_all,ShotsOnTarget_Rolling5_all,Corners_Rolling5_all,Fouls_Rolling5_all,TablePosDiff_Rolling10_all,GoalsFor_Rolling10_all,Shots_Rolling10_all,ShotsOnTarget_Rolling10_all,Corners_Rolling10_all,Fouls_Rolling10_all
0,2023-08-12,12:30,Arsenal,Nott'm Forest,H,2,1,2,0,15,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-08-21,20:00,Arsenal,Crystal Palace,A,1,0,0,0,14,...,15.00,7.0,8.0,12.000000,0.0,2.000000,15.00,7.0,8.0,12.000000
2,2023-08-26,15:00,Arsenal,Fulham,H,2,2,0,1,19,...,14.50,5.0,8.0,11.000000,0.0,1.500000,14.50,5.0,8.0,11.000000
3,2023-09-03,16:30,Arsenal,Man United,H,3,1,1,1,17,...,16.00,7.0,8.0,9.333333,0.0,1.666667,16.00,7.0,8.0,9.333333
4,2023-09-17,16:30,Arsenal,Everton,A,1,0,0,0,13,...,16.25,6.5,9.0,9.000000,1.0,2.000000,16.25,6.5,9.0,9.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
755,2024-04-24,19:45,Wolves,Bournemouth,H,0,1,0,1,15,...,10.20,3.8,2.8,14.000000,1.0,0.900000,11.30,3.9,3.8,12.000000
756,2024-04-27,15:00,Wolves,Luton,H,2,1,1,0,13,...,10.60,4.0,3.6,12.200000,0.6,0.900000,11.10,3.8,3.9,11.900000
757,2024-05-04,17:30,Wolves,Man City,A,1,5,0,3,2,...,11.60,4.6,3.6,12.600000,1.7,0.900000,11.20,3.6,3.9,12.000000
758,2024-05-11,15:00,Wolves,Crystal Palace,H,1,3,0,2,13,...,9.20,3.4,2.8,13.000000,-0.1,0.900000,10.10,3.5,3.4,12.900000
759,2024-05-19,16:00,Wolves,Liverpool,A,0,2,0,2,4,...,9.60,4.0,4.2,13.600000,0.0,1.000000,10.20,3.9,3.7,13.100000

In [ ]:
home_features = team_df[team_df['Venue'] == 'H'].copy()
away_features = team_df[team_df['Venue'] == 'A'].copy()

home_features = home_features.add_prefix('Home_')
away_features = away_features.add_prefix('Away_')

home_features = home_features.rename(columns={
    'Home_Date': 'Date',
    'Home_Team': 'HomeTeam'
})

away_features = away_features.rename(columns={
    'Away_Date': 'Date',
    'Away_Team': 'AwayTeam'
})

matches = dfpl23.copy()

matches = matches.merge(
    home_features,
    on=['Date', 'HomeTeam'],
    how='left'
)

matches = matches.merge(
    away_features,
    on=['Date', 'AwayTeam'],
    how='left'
)

matches = matches.dropna()

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,Away_Shots_Rolling5_all,Away_ShotsOnTarget_Rolling5_all,Away_Corners_Rolling5_all,Away_Fouls_Rolling5_all,Away_TablePosDiff_Rolling10_all,Away_GoalsFor_Rolling10_all,Away_Shots_Rolling10_all,Away_ShotsOnTarget_Rolling10_all,Away_Corners_Rolling10_all,Away_Fouls_Rolling10_all
0,2023-08-11,20:00,Burnley,Man City,0,3,A,0,2,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023-08-12,12:30,Arsenal,Nott'm Forest,2,1,H,2,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023-08-12,15:00,Bournemouth,West Ham,1,1,D,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023-08-12,15:00,Brighton,Luton,4,1,H,1,0,H,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023-08-12,15:00,Everton,Fulham,0,1,A,0,0,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2024-05-19,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,H,...,11.0,3.2,4.8,9.8,4.2,1.7,10.8,3.3,6.0,11.1
376,2024-05-19,16:00,Liverpool,Wolves,2,0,H,2,0,H,...,9.6,4.0,4.2,13.6,0.0,1.0,10.2,3.9,3.7,13.1
377,2024-05-19,16:00,Luton,Fulham,2,4,A,1,2,A,...,11.0,4.2,3.2,8.8,-2.3,1.2,15.0,5.0,6.1,9.5
378,2024-05-19,16:00,Man City,West Ham,3,1,H,2,1,H,...,13.4,4.6,5.2,8.4,2.8,1.6,13.4,4.4,5.4,9.4
379,2024-05-19,16:00,Sheffield United,Tottenham,0,3,A,0,1,A,...,15.0,5.0,7.2,12.8,4.8,1.2,14.7,4.7,6.4,12.2

In [72]:
matches = matches.dropna()
matches

,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,HTR,...,Away_Shots_Rolling5_all,Away_ShotsOnTarget_Rolling5_all,Away_Corners_Rolling5_all,Away_Fouls_Rolling5_all,Away_TablePosDiff_Rolling10_all,Away_GoalsFor_Rolling10_all,Away_Shots_Rolling10_all,Away_ShotsOnTarget_Rolling10_all,Away_Corners_Rolling10_all,Away_Fouls_Rolling10_all
19,2023-08-25,20:00,Chelsea,Luton,3,0,H,1,0,H,...,9.0,3.0,7.0,12.0,0.0,1.0,9.0,3.0,7.0,12.0
20,2023-08-26,12:30,Bournemouth,Tottenham,0,2,A,0,1,A,...,17.5,6.0,5.5,11.0,0.0,2.0,17.5,6.0,5.5,11.0
21,2023-08-26,15:00,Arsenal,Fulham,2,2,D,0,1,A,...,9.5,2.0,4.5,9.5,0.0,0.5,9.5,2.0,4.5,9.5
22,2023-08-26,15:00,Brentford,Crystal Palace,1,1,D,1,0,H,...,19.0,5.0,3.0,12.5,0.0,0.5,19.0,5.0,3.0,12.5
23,2023-08-26,15:00,Everton,Wolves,0,1,A,0,0,D,...,19.5,5.5,6.0,12.0,0.0,0.5,19.5,5.5,6.0,12.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
375,2024-05-19,16:00,Crystal Palace,Aston Villa,5,0,H,2,0,H,...,11.0,3.2,4.8,9.8,4.2,1.7,10.8,3.3,6.0,11.1
376,2024-05-19,16:00,Liverpool,Wolves,2,0,H,2,0,H,...,9.6,4.0,4.2,13.6,0.0,1.0,10.2,3.9,3.7,13.1
377,2024-05-19,16:00,Luton,Fulham,2,4,A,1,2,A,...,11.0,4.2,3.2,8.8,-2.3,1.2,15.0,5.0,6.1,9.5
378,2024-05-19,16:00,Man City,West Ham,3,1,H,2,1,H,...,13.4,4.6,5.2,8.4,2.8,1.6,13.4,4.4,5.4,9.4
379,2024-05-19,16:00,Sheffield United,Tottenham,0,3,A,0,1,A,...,15.0,5.0,7.2,12.8,4.8,1.2,14.7,4.7,6.4,12.2